### ISSUE TITLE
Method chatPostMessage() with "blocks" return "invalid_blocks_format"

### ISSUE THREAD

**Issue by ASR-WIR** [jolicode/slack-php-api#114]
Lib version: v4.1.1
PHP: 7.4.16 

Hi, your lib is great! But i have problem with sending Blocks with `chatPostMessage()` method. I am trying everything and it does not work. I get response `invalid_blocks_format` from Slack. 

My code looks like this:
```
$client->chatPostMessage([
            'channel' => '#channel',
            'username' => 'BOT',
            'blocks' => <<<EOT
{
	"blocks": [
		{
			"type": "section",
			"text": {
				"type": "plain_text",
				"text": "This is a plain text section block.",
				"emoji": true
			}
		}
	]
}
EOT]);
```

Could you check if everything is working properly?

**Comment by damienalexandre** [comment]
Hi!

Thanks for reaching out,
I think this is a JSON escaping issue. You pass a JSON that has two times the "blocks" name :thinking: 

You can find a nice working example here:

https://github.com/jolicode/slack-php-api/blob/6e4b7c83ab172884ad29cf7517841b7ba7ba4c82/tests/WritingTest.php#L54-L87

**Comment by ASR-WIR** [comment]
Thank you very much, it works! :) 

Could you add this example into `doc/examples`? It would be great!

**Comment by damienalexandre** [comment]
Just done that :+1: :heavy_check_mark: 

Have a good day.
