### ISSUE TITLE
ChatUpdate Endpoint - Replace float TS by string TS 

### ISSUE THREAD

**Issue by mihani** [jolicode/slack-php-api#12]
Hello,

When I used this lib to update an slack message I found an issue. In `JoliCode\Slack\Api\Endpoint\ChatUpdate`, getFormOptionsResolver allow a float for the Slack TS then I read the slack api doc Slack TS is a string.

To fix this issue I override
```php
        $optionsResolver->setAllowedTypes('ts', ['float']);
```
by
```php
        $optionsResolver->setAllowedTypes('ts', ['string']);
```
After then it's works but I don't know if there are BC somewhere.

**Comment by damienalexandre** [comment]
As we can see, the official OpenAPI specification mark this field as "number":

https://github.com/slackapi/slack-api-specs/blob/fbfd2921822d4d7846491f863025dc3043fa85c2/web-api/slack_web_openapi_v2.json#L7108-L7113

The documentation is not clear about the type:

![image](https://user-images.githubusercontent.com/225704/53556767-ce82bc00-3b44-11e9-9ffa-612598feb6ea.png)

But in the provided example there is a string:

![image](https://user-images.githubusercontent.com/225704/53556798-e5291300-3b44-11e9-8d52-24d0b21280d8.png)

As the specification is wrong, so is our PHP Client expected types. 
Do you mind send a patch for the specification?
https://github.com/jolicode/slack-php-api/blob/master/doc/updating-sdk.md

If you can't do it, let us know :+1:

**Comment by mihani** [comment]
PR #13 to fix this issue.

**Comment by damienalexandre** [comment]
Fixed and released :+1:
