### ISSUE TITLE
Method does not specify that exception might be thrown. 

### ISSUE THREAD

**Issue by Legion112** [jolicode/slack-php-api#127]
![image](https://user-images.githubusercontent.com/20613430/133806080-e03ad4ad-6b10-4988-a5c1-2ba77211e719.png)
Here I expect to see throws doc block to make my Static Analyze Tool help me to process the error.

**Comment by Legion112** [comment]
executeEndpoint might throw exception

**Comment by lyrixx** [comment]
Hello,

Maintaining @throw PHPDoc is very time consuming for maintainers.
And this issue did not get much tractions.

So I think we can close this issue.

Anyway, thanks for raising your point.

**Comment by Legion112** [comment]
Why is it hard to maintain?
Configuring a static analyzer inside the project will force you to explicitly write throw doc block to improve library usability. 

I disagree about it is hard to maintain. if this will be part of the pipeline, it quite easy for anyone who works on code in the library to correct their pull request.

**Comment by lyrixx** [comment]
We had a similar request on [another repo](https://github.com/jolicode/elastically/pull/160#issuecomment-1506641725) and we deciced to not add them.

I let you read the answer there.

---

And as you said, almost all code here a generated. So the issue should be open in the other repo.

I'm closing. Thanks for your understanding
