### ISSUE TITLE
Some values not reachable?

### ISSUE THREAD

**Issue by catasuisse** [jolicode/slack-php-api#134]
Could it be that the values «presence» and (for me important) «fields» of a user and its profile aren't reachable?

<img width="802" alt="Bildschirmfoto 2021-12-17 um 21 57 21" src="https://user-images.githubusercontent.com/48312852/146572560-9aca1b65-1872-4f05-a526-d09e20af4be4.png">

**Comment by catasuisse** [comment]
Sorry! I found out. It was on the part of Slack. If someone else wants to read cutom fields:

`$client->usersProfileGet(['user' => 'USER_ID'])`

**Comment by lyrixx** [comment]
hello, so I can close the issue?

**Comment by catasuisse** [comment]
> hello, so I can close the issue?

👍

**Comment by lyrixx** [comment]
Thanks for the feedback and the explanation
