### ISSUE TITLE
UsersList and UsergroupsList should accept new parameter: "team_id"

### ISSUE THREAD

**Issue by mpyw** [jolicode/slack-php-api#137]
API specs with JSON schema do not contain parameter "team_id":

- https://github.com/slackapi/slack-api-specs/blob/bc08db49625630e3585bf2f1322128ea04f2a7f3/web-api/slack_web_openapi_v2_without_examples.json#L21888-L21913
- https://github.com/slackapi/slack-api-specs/blob/bc08db49625630e3585bf2f1322128ea04f2a7f3/web-api/slack_web_openapi_v2_without_examples.json#L20546-L20572

but it appears on official Web documentation:

- https://api.slack.com/methods/users.list 
- https://api.slack.com/methods/usergroups.list 

-----

Currently I'm patching like this :(

```php
$response = $this->client->executeEndpoint(new class ($params) extends Endpoint\UsersList {
    protected function getQueryOptionsResolver(): OptionsResolver
    {
        $resolver = parent::getQueryOptionsResolver();
        $resolver->define('team_id');
        $resolver->setAllowedTypes('team_id', ['string']);

        return $resolver;
    }
});
```

```php
$response = $this->client->executeEndpoint(new class ($params) extends Endpoint\UsergroupsList {
    protected function getQueryOptionsResolver(): OptionsResolver
    {
        $resolver = parent::getQueryOptionsResolver();
        $resolver->define('team_id');
        $resolver->setAllowedTypes('team_id', ['string']);

        return $resolver;
    }
});
```

**Comment by mpyw** [comment]
Related: #129

Also missing for ConversationsList

**Comment by damienalexandre** [comment]
Thanks for reporting this :+1: Indeed we need to patch the specification again, following this tutorial: https://github.com/jolicode/slack-php-api/blob/main/docs/4-updating-sdk.md.

As you can see we maintain a patch file https://github.com/jolicode/slack-php-api/blob/main/resources/slack-openapi-sorted.patch for the official specification as it often broken or wrong.

Is that something you would like to give a try?
