### ISSUE TITLE
Question: Recommended endpoint for `response_url`

### ISSUE THREAD

**Issue by matthewnessworthy** [jolicode/slack-php-api#144]
Is there a recommended way of handling messages in response to interactivity?
see https://api.slack.com/interactivity/handling#message_responses

The Slack docs return a URL that you POST to, is there a way to make this call via `jolicode/slack-php-api` for consistent response handling?

**Comment by matthewnessworthy** [comment]
@damienalexandre maybe you have some thoughts on this?

**Comment by damienalexandre** [comment]
That would require a custom Endpoint class, 
to be given to:

 https://github.com/jolicode/slack-php-api/blob/6be6f485b602c7edb383389fc19f32aff75f0320/generated/Runtime/Client/Client.php#L52

Extending the proper endpoint to add a setter for https://github.com/jolicode/slack-php-api/blob/6be6f485b602c7edb383389fc19f32aff75f0320/generated/Endpoint/AdminAppsApprove.php#L46 could work, this can by used directly by our client https://github.com/jolicode/slack-php-api/blob/main/src/Client.php which extends the one generated by Jane.

**Comment by matthewnessworthy** [comment]
Thanks,
That makes sense :)
