### ISSUE TITLE
Missing @throws in the phpdocs

### ISSUE THREAD

**Issue by pmishev** [jolicode/slack-php-api#149]
This is pretty much a duplicate of https://github.com/jolicode/slack-php-api/issues/126, which was closed without an actual solution.
The phpdocs are not correct and it's causing very annoying problems with static code checks.
Is there a reason why you can't add `@throws SlackErrorResponse` ?

**Comment by lyrixx** [comment]
Hello,

Maintaining `@throw` PHPDoc is very time consuming for maintainers. 
And this issue did not get much tractions.

So I think we can close this issue.

Anyway, thanks for raising your point.

**Comment by lyrixx** [comment]
Duplicates of #127.
