### ISSUE TITLE
PHP>=8.2 Creation of dynamic property is deprecated 

### ISSUE THREAD

**Issue by divinity76** [jolicode/slack-php-api#164]
as of PHP8.2

><b>Deprecated</b>:  Creation of dynamic property JoliCode\Slack\Api\Endpoint\ChatPostMessage::$formParameters is deprecated in <b>/var/www/vendor/jolicode/slack-php-api/generated/Endpoint/ChatPostMessage.php</b> on line <b>50</b><br />

a quickfix would be to add 
```php
    /** @var array */
    public $formParameters = [];
```
to `generated/Runtime/Client/EndpointTrait.php` , but how to make the GENERATOR add that, i have no idea.

PR #161 tried to fix it (but did not address the generator issue)

**Comment by damienalexandre** [comment]
This should be fixed with the latest release v4.7.0 :tada:

**Comment by divinity76** [comment]
@damienalexandre  with just reading through the code, i fail to see how that update could have fixed it: JoliCode\Slack\Api\Endpoint\ChatPostMessage::formParameters still reference `$this->formParameters` which is not declared in any of `generated/Endpoint/ChatPostMessage.php` and `generated/Runtime/Client/EndpointTrait.php`  and `generated/Runtime/Client/Endpoint.php` , am i missing something?

**Comment by damienalexandre** [comment]
It can be seen here: https://github.com/jolicode/slack-php-api/blob/86f0b47862d045a6cffa8974d60e67350daa79df/generated/Runtime/Client/BaseEndpoint.php#L23

**Comment by divinity76** [comment]
somehow missed it, thanks!
