### ISSUE TITLE
Allow for jane-php/open-api-runtime version 7.7.0

### ISSUE THREAD

**Issue by jurgenhaas** [jolicode/slack-php-api#169]
The current constraint is `jane-php/open-api-runtime: ~7.6.0` and that doesn't allow to update to the latest minor which just got released.

**Comment by damienalexandre** [comment]
Hello, would you be able to send a pull request for this change? 

Thanks a lot

**Comment by jurgenhaas** [comment]
Done.

**Comment by damienalexandre** [comment]
Client v4.7.1 is released with your fix, thanks!
