### ISSUE TITLE
Milestone: Create new release

### ISSUE THREAD

**Issue by Niko9911** [jolicode/slack-php-api#38]
As there is changes in the repo, when you're done with changes, please create new release tag, so we can use it in the composer.

**Comment by damienalexandre** [comment]
Yes I'm fixing two more issues before the next release, scheduled for today.

**Comment by damienalexandre** [comment]
Release 1.2.0 is out: https://packagist.org/packages/jolicode/slack-php-api

Thank to [JoliCode](https://jolicode.com/) for sponsoring my Open Source time!
