### ISSUE TITLE
chatUpdate -> 'ts' requiring float that PHP can never satisfy

### ISSUE THREAD

**Issue by runthis** [jolicode/slack-php-api#42]
PHP will never be able to satisfy this float
1562189704.014800

Sending Slack a string of "1562189704.014800" works perfectly fine.

PHP literally does not have the ability to maintain 1562189704.014800 as a float. It will always remove the trailing zeros unless its a string.

$optionsResolver->setAllowedTypes('text', ['float']);

should be

$optionsResolver->setAllowedTypes('text', ['string']);

If this already exists in a newer version please let me know. Thanks for an awesome tool by the way!

**Comment by runthis** [comment]
I saw the other posts where this was closed. Slack accepts a string, there is no reason to not make this a string in this heavily undocumented API

**Comment by GreenSuslik** [comment]
Yep! Php create from string = "1567091229.010100" float = 1567091229.0101

**Comment by GreenSuslik** [comment]
It's fix in https://github.com/jolicode/slack-php-api/pull/45

**Comment by damienalexandre** [comment]
#45 has been released! Could you report if this issue can be closed?

Thanks!

**Comment by GreenSuslik** [comment]
I have checked, all ok.

**Comment by damienalexandre** [comment]
Awesome, thanks!!
