### ISSUE TITLE
works great docs suck

### ISSUE THREAD

**Issue by timrabbetts** [jolicode/slack-php-api#46]
Hi,

Finally figured it out, I have update the readme on my loocal clone to make it easier to understand, how do I push this raise pull request so you might want this?

**Comment by timrabbetts** [comment]
e.g 

## Usage

Slack used to have a custom integerations section, allot of docs use this, but the new way is building an app.

You need to create an app and get the token for that app to communicate with slack.
- goto https://api.slack.com/apps
- create an app with bot option
- once app created goto the OAuth & Permissions section where you will find a Bot User OAuth Access Token, thats the token you need to add to the code.
- you can get your user id going to the profile and account section of the web based desktop app, its the last value in the url at the top, starts with U or W.

Then, use the factory that is provided to create the client:

There are some good examples in this repo /doc/examples

**Comment by lyrixx** [comment]
Hello

> how do I push this raise pull request so you might want this?

https://en.lmgtfy.com/?q=how%20to%20make%20a%20pull%20request%20on%20github

**Comment by dev-mansonthomas** [comment]
I agree that docs could be improved :)

I'm stuck with this error : 
Slack returned error code "missing_scope"

And I don't feel it's specified in the example or docs here what to do with scope.

from the slack doc : https://api.slack.com/legacy/oauth-scopes
it seems we have to make some calls to setup scopes.

**Comment by dev-mansonthomas** [comment]
Found it here : 
https://api.slack.com/authentication/basics

> You can select the scopes to add to your app by heading over to the OAuth & Permissions sidebar.
> 
> Scroll down to the Scopes section and click to Add an OAuth Scope.
> 
> For example, try adding the chat:write scope to your Bot Token. It'll allow your app to post messages! 


Now I get a channel not found, while I specify the correct channel name...

**Comment by dev-mansonthomas** [comment]
> Hello
> 
> > how do I push this raise pull request so you might want this?
> 
> Thanks for proposing a pull request. You can read the doc about it [there](https://en.lmgtfy.com/?q=how%20to%20make%20a%20pull%20request%20on%20github)

I've made a pull request ;)
