### ISSUE TITLE
Parameters for chatDeleteScheduledMessage

### ISSUE THREAD

**Issue by kesowins** [jolicode/slack-php-api#66]
Hello,

i wanted to delete a scheduled Chatmessage, but the Method chatDeleteScheduledMessage got only one string Param (string $fetch). How can i set the param like the scheduledMessageId and the channelid? I need both of them to delete the Message in Slack.

Greetings

**Comment by pyrech** [comment]
Hello, sorry it took so long to answer here. There was a bit of inactivity lately.

It looks like sadly Slack didn't describe the parameters for this particular endpoint. Fortunately we have a patch system to update the spec on our side. Would you like to give it a try and update the SDK to describe the missing parameters? We have a documentation explaining how to do that: https://github.com/jolicode/slack-php-api/blob/master/doc/updating-sdk.md#generating-a-new-patch

Don't worry if you can't, we will give a look when we got some time :wink:

**Comment by damienalexandre** [comment]
I believe it has been fixed in our latest release:

https://github.com/jolicode/slack-php-api/blob/4f8cd6ada7ef89eebae71250068c84cbe0fb2d71/generated/Endpoint/ChatDeleteScheduledMessage.php#L23-L28

Thanks for reporting this issue,
Cheers
