### ISSUE TITLE
Support for views.open

### ISSUE THREAD

**Issue by tzsk** [jolicode/slack-php-api#67]
Awesome package. Love it.

It would be great to have support for block surface triggers.

Eg. `views.open`

**Comment by pyrech** [comment]
Hello, thanks for your kind support :slightly_smiling_face: 

Looks like Slack didn't describe these endpoints in their specification yet. We must either:
- wait until they add those missing methods in their spec
- or update the spec on our side.

Unfortunately I don't have enough time to add all these methods right now. If you're familiar with OpenAPI/Swagger specifications, you can try to describe these methods and update the SDK yourself :muscle:

We have some documentation explaining how to do that: https://github.com/jolicode/slack-php-api/blob/master/doc/updating-sdk.md#generating-a-new-patch If you need some help or have question, I would be glad to answer them :wink:

**Comment by damienalexandre** [comment]
Hi!

Slack updated their specification and so did we, 
ViewsOpen is now part of the endpoints we support: https://github.com/jolicode/slack-php-api/blob/master/generated/Endpoint/ViewsOpen.php

I'm closing this issue now and feel free to get in touch if you found other missing endpoint!

Cheers
