### ISSUE TITLE
ChatGetPermalink endpoint: change message_ts type to string

### ISSUE THREAD

**Issue by StyxUA** [jolicode/slack-php-api#75]
Similar to #12, #22, #26 and #27.

**Comment by pyrech** [comment]
It looks like they is a lot of inconsistencies in how Slack describes/provides their timestamp :laughing: 

We would be very glad if you could open a PR to fix this endpoint :wink: We have some documentation explaining how to update the SDK: https://github.com/jolicode/slack-php-api/blob/master/doc/updating-sdk.md#generating-a-new-patch

Do not hesitate to ask questions or for some help  here :wink:

**Comment by damienalexandre** [comment]
I think this issue is resolved already:

https://github.com/jolicode/slack-php-api/blob/4f8cd6ada7ef89eebae71250068c84cbe0fb2d71/generated/Endpoint/ChatGetPermalink.php#L67

Feel free to reopen if you still have any problem with the message_ts.
