### ISSUE TITLE
Issues with league/uri dependency of jane

### ISSUE THREAD

**Issue by dinamic** [jolicode/slack-php-api#79]
The jane library that's currently a dependency uses an old version of league/uri. I hope that dependency would get updated soon. Here's the progress on it: https://github.com/janephp/janephp/issues/294

Could we please have a new release tagged once it's fixed in jane?

**Comment by pyrech** [comment]
I just make an install of this package and got `league/uri` 6.2.1 with it so i guess there is nothing to do here :wink:

Do not hesitate to reopen if you still have the old dependency.
