### ISSUE TITLE
composer won't install dependencies

### ISSUE THREAD

**Issue by nekromoff** [jolicode/slack-php-api#8]
Using version ^1.7 for php-http/curl-client
Using version ^1.5 for guzzlehttp/psr7
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install php-http/curl-client v1.7.1
    - Conclusion: don't install php-http/curl-client v1.7.0|remove php-http/httplug v2.0.0
    - Conclusion: don't install php-http/curl-client v1.7.0|don't install php-http/httplug v2.0.0
    - Installation request for php-http/curl-client ^1.7 -> satisfiable by php-http/curl-client[v1.7.0, v1.7.1].
    - php-http/curl-client v1.7.0 requires php-http/httplug ^1.0 -> satisfiable by php-http/httplug[v1.0.0, v1.1.0].
    - Can only install one of: php-http/httplug[v1.0.0, v2.0.0].
    - Can only install one of: php-http/httplug[v1.1.0, v2.0.0].
    - Installation request for php-http/httplug (locked at v2.0.0) -> satisfiable by php-http/httplug[v2.0.0].

Installation failed, reverting ./composer.json to its original content.

**Comment by damienalexandre** [comment]
That may be because we require Httplug 1.7:

https://github.com/jolicode/slack-php-api/blob/c212c91ead97a5ae4dadc14218b07200565e12c8/composer.json#L29

HTTPlug 2 is not yet released: https://packagist.org/packages/php-http/client-common#1.8.2

Why do you have HTTPlug 2? Are you testing it? Could you show your composer.json file?

**Comment by simontuck** [comment]
Same issue. HTTPlug 2 has been released (https://github.com/php-http/httplug/releases). I require php-http/curl-client which requires php-http/httplug ^2.0

**Comment by pyrech** [comment]
Support for HTTPlug 2 has just been released in v1.1.1.
Enjoy 🎉
