### ISSUE TITLE
chatPostMessage and attachments

### ISSUE THREAD

**Issue by vilain-corentin** [jolicode/slack-php-api#81]
Hello,

First of all, congratulations on the code!

I'm trying to pass an attachment to the Slack message using the chatPostMessage() method but I can't get it through.

I have 2 problems,
- No matter what I put in $attachments, I get the mistake:
Slack returned error code "no_text."

- I don't understand what kind of thong format I'm supposed to fill out? Can you give me an example?

Thank you in advance and have a nice day.

**Comment by damienalexandre** [comment]
Hi @vilain-corentin;
did you resolve your issue?

For reference we have an attachment example here:

https://github.com/jolicode/slack-php-api/blob/28967f79835df4266da5d18979b0a78986a7d62f/tests/WritingTest.php#L28-L36

Cheers
