### ISSUE TITLE
A PHP Error was encountered Severity: Compile Error

### ISSUE THREAD

**Issue by ironwill1023** [jolicode/slack-php-api#84]
Hi, Guys!
I've encountered this error on Ubuntu 18.04.
https://prnt.sc/trit7j

Any help, plz?

**Comment by damienalexandre** [comment]
Hi!

Could you tell us what PHP version you are using? (run `php -v` in a terminal).

Thanks

**Comment by damienalexandre** [comment]
Hi again,
it looks a lot like the error we got with PHP8 (https://github.com/jolicode/slack-php-api/issues/99) - as this is now fixed and we don't know what PHP Version you are using, I'm going to close this issue.

Please feel free to reopen with more informations.

Cheers!
