### ISSUE TITLE
Scheduling messages expects the post_at attribute to be string while slack returns an integer

### ISSUE THREAD

**Issue by ScSherifTarek** [jolicode/slack-php-api#92]
When scheduling a message using the following code:
```
$client->chatScheduleMessage([
    'channel'=> 'testing-slack-apps',
    'text'=> 'Hey, This is a scheduled message :tada:',
    'post_at'=> 1599654720
]);
```

I got the following error because the package is expecting the post_at attribute to be of type string.
![image](https://user-images.githubusercontent.com/69537692/92599419-86e8fe80-f2aa-11ea-9e8e-6e6dc5c81910.png)

so I have changed the post_at attribute to be of type string as follows:
```
$client->chatScheduleMessage([
    'channel'=> 'testing-slack-apps',
    'text'=> 'Hey, This is a scheduled message :tada:',
    'post_at'=> '1599654720'
]);
```
now it works and the message gets scheduled successfully, but now another exception is throwed, saying that `JoliCode\Slack\Api\Model\ChatScheduleMessagePostResponse200::setPostAt()` is expecting the post_at parameter to be of type string, but actually slack returns it as an integer.

![image](https://user-images.githubusercontent.com/69537692/92598636-5eacd000-f2a9-11ea-964c-70770de0577b.png)

I believe that it doesn't have to be of type string since slack is expecting it as an integer representing the UNIX timestamp.

**Comment by damienalexandre** [comment]
Thanks for reporting! I just submitted a PR that address this issue.
